In [1]:
import plotly.graph_objs as go
import pandas as pd
from plotly.offline import iplot
import numpy as np
import statistics 
import plotly.express as px
from numpy.lib import recfunctions as rfn

In [2]:
e12_t05_rawCount_data = pd.read_csv("/Users/krilowcn/Desktop/Projects/GSIS/data/normalizedData/200613_E12_logNorm/200613_E12-05_logNorm.csv.gz", sep=",", index_col=0,low_memory=False) #pandas DataFrame
e12_t06_rawCount_data = pd.read_csv("/Users/krilowcn/Desktop/Projects/GSIS/data/normalizedData/200613_E12_logNorm/200613_E12-06_logNorm.csv.gz", sep=",", index_col=0,low_memory=False) #pandas DataFrame
e12_t09_rawCount_data = pd.read_csv("/Users/krilowcn/Desktop/Projects/GSIS/data/normalizedData/200613_E12_logNorm/200613_E12-09_logNorm.csv.gz", sep=",", index_col=0,low_memory=False) #pandas DataFrame
e12_t10_rawCount_data = pd.read_csv("/Users/krilowcn/Desktop/Projects/GSIS/data/normalizedData/200613_E12_logNorm/200613_E12-10_logNorm.csv.gz", sep=",", index_col=0,low_memory=False) #pandas DataFrame
e12_t13_rawCount_data = pd.read_csv("/Users/krilowcn/Desktop/Projects/GSIS/data/normalizedData/200613_E12_logNorm/200613_E12-13_logNorm.csv.gz", sep=",", index_col=0,low_memory=False) #pandas DataFrame
e12_t14_rawCount_data = pd.read_csv("/Users/krilowcn/Desktop/Projects/GSIS/data/normalizedData/200613_E12_logNorm/200613_E12-14_logNorm.csv.gz", sep=",", index_col=0,low_memory=False) #pandas DataFrame
e12_t17_rawCount_data = pd.read_csv("/Users/krilowcn/Desktop/Projects/GSIS/data/normalizedData/200613_E12_logNorm/200613_E12-17_logNorm.csv.gz", sep=",", index_col=0,low_memory=False) #pandas DataFrame
e12_t18_rawCount_data = pd.read_csv("/Users/krilowcn/Desktop/Projects/GSIS/data/normalizedData/200613_E12_logNorm/200613_E12-18_logNorm.csv.gz", sep=",", index_col=0,low_memory=False) #pandas DataFrame
e12_t21_rawCount_data = pd.read_csv("/Users/krilowcn/Desktop/Projects/GSIS/data/normalizedData/200613_E12_logNorm/200613_E12-21_logNorm.csv.gz", sep=",", index_col=0,low_memory=False) #pandas DataFrame
e12_t22_rawCount_data = pd.read_csv("/Users/krilowcn/Desktop/Projects/GSIS/data/normalizedData/200613_E12_logNorm/200613_E12-22_logNorm.csv.gz", sep=",", index_col=0,low_memory=False) #pandas DataFrame


cell_types = pd.read_csv("/Users/krilowcn/Desktop/Projects/GSIS/data/normalizedData/200613_E12_logNorm/200613_E12_cell_type.txt", sep="\t") #pandas DataFrame for cell types

In [3]:
cell_types_list = ['Alpha','Beta','Delta','Gamma','Epsilon'] #the cell types of interest for this work
cell_types = cell_types[cell_types['CellType'].isin(cell_types_list)] # parsing sampele type list, to only contain the cell types of interest
cell_types.reset_index(drop=True, inplace=True)

updated_list = []
for t in cell_types['SampleID'].values:
    if t in ['E12-05', 'E12-06']:
        updated_list.append('2Hr')
    elif t in ['E12-09','E12-10']:
        updated_list.append('4Hr')
    elif t in ['E12-13','E12-14']:
        updated_list.append('8Hr')
    elif t in ['E12-17','E12-18']:
        updated_list.append('12Hr')
    elif t in ['E12-21','E12-22']:
        updated_list.append('24Hr')
    else:
        updated_list.append('NA')
cell_types['TimePoint'] = updated_list

In [4]:
# Data dict
sample_dict = {
    'E12-05': pd.read_csv("/Users/krilowcn/Desktop/Projects/GSIS/data/normalizedData/200613_E12_logNorm/200613_E12-05_logNorm.csv.gz", sep=",", index_col=0,low_memory=False),
    'E12-06': pd.read_csv("/Users/krilowcn/Desktop/Projects/GSIS/data/normalizedData/200613_E12_logNorm/200613_E12-06_logNorm.csv.gz", sep=",", index_col=0,low_memory=False),  
    'E12-09': pd.read_csv("/Users/krilowcn/Desktop/Projects/GSIS/data/normalizedData/200613_E12_logNorm/200613_E12-09_logNorm.csv.gz", sep=",", index_col=0,low_memory=False),  
    'E12-10': pd.read_csv("/Users/krilowcn/Desktop/Projects/GSIS/data/normalizedData/200613_E12_logNorm/200613_E12-10_logNorm.csv.gz", sep=",", index_col=0,low_memory=False),  
    'E12-13': pd.read_csv("/Users/krilowcn/Desktop/Projects/GSIS/data/normalizedData/200613_E12_logNorm/200613_E12-13_logNorm.csv.gz", sep=",", index_col=0,low_memory=False),  
    'E12-14': pd.read_csv("/Users/krilowcn/Desktop/Projects/GSIS/data/normalizedData/200613_E12_logNorm/200613_E12-14_logNorm.csv.gz", sep=",", index_col=0,low_memory=False),  
    'E12-17': pd.read_csv("/Users/krilowcn/Desktop/Projects/GSIS/data/normalizedData/200613_E12_logNorm/200613_E12-17_logNorm.csv.gz", sep=",", index_col=0,low_memory=False),  
    'E12-18': pd.read_csv("/Users/krilowcn/Desktop/Projects/GSIS/data/normalizedData/200613_E12_logNorm/200613_E12-18_logNorm.csv.gz", sep=",", index_col=0,low_memory=False),  
    'E12-21': pd.read_csv("/Users/krilowcn/Desktop/Projects/GSIS/data/normalizedData/200613_E12_logNorm/200613_E12-21_logNorm.csv.gz", sep=",", index_col=0,low_memory=False),  
    'E12-22': pd.read_csv("/Users/krilowcn/Desktop/Projects/GSIS/data/normalizedData/200613_E12_logNorm/200613_E12-22_logNorm.csv.gz", sep=",", index_col=0,low_memory=False),  
}

In [15]:
cells = pd.DataFrame([], columns = ['gene', 'mean_expr_1', 'mean_expr_2', 'cell_type', 'time_point'])

for cell_type in np.unique(cell_types['CellType']):
    if cell_type == "unknown":
        continue
    sub_cells = cell_types[cell_types.CellType == cell_type]
    for time_point in np.unique(cell_types['TimePoint']):
        sampls = np.unique(cell_types[cell_types.TimePoint == time_point]['SampleID'])
        counts_1 = sample_dict.get(sampls[0]) #Getting sample IDs
        counts_2 = sample_dict.get(sampls[1])
        
        if counts_1 is None or counts_2 is None:
            continue
        
        barcodes_1 = sub_cells[sub_cells.SampleID == sampls[0]]['CellID'].values
        barcodes_2 = sub_cells[sub_cells.SampleID == sampls[1]]['CellID'].values
        means_1 = np.mean(counts_1.loc[:, barcodes_1],axis=1) 
        means_2 = np.mean(counts_2.loc[:, barcodes_2],axis=1)
        joint_index = np.intersect1d(means_1.index.values, means_2.index.values)

        cells = cells.append( 
            pd.DataFrame({
                'gene': joint_index,
                'mean_expr_1': means_1.loc[joint_index].values,
                'mean_expr_2': means_2.loc[joint_index].values,
                'cell_type': [cell_type] * len(joint_index),
                'time_point': [time_point] * len(joint_index)  
            }))

In [27]:
cells[(cells['cell_type']=='Epsilon') & (cells['time_point']=='24Hr')]

         gene  mean_expr_1  mean_expr_2 cell_type time_point
0        A1BG     0.082587     0.274570   Epsilon       24Hr
1        A1CF     0.628651     1.301590   Epsilon       24Hr
2         A2M     0.000000     0.000000   Epsilon       24Hr
3      A4GALT     0.320717     0.310116   Epsilon       24Hr
4        AAAS     0.261465     0.000000   Epsilon       24Hr
...       ...          ...          ...       ...        ...
10965    ZW10     0.000000     0.000000   Epsilon       24Hr
10966    ZXDC     0.000000     0.000000   Epsilon       24Hr
10967  ZYG11B     0.178878     0.000000   Epsilon       24Hr
10968     ZYX     0.000000     0.000000   Epsilon       24Hr
10969   ZZEF1     0.296514     0.711083   Epsilon       24Hr

[10970 rows x 5 columns]

In [9]:
list_ordering = ['2Hr','4Hr', '8Hr','12Hr','24Hr']  
cells["time_point"] = pd.Categorical(cells["time_point"], categories=list_ordering)

In [12]:
import plotnine as plt9
from plotnine import *
from plotnine.data import *

%matplotlib inline

plt9.options.figure_size = (22,10)

plt9.ggplot(cells, plt9.aes(
    x='mean_expr_1', 
    y = 'mean_expr_2')) + plt9.geom_point(
        alpha=0.50) + geom_abline(intercept=0, 
    slope=1) + plt9.facet_grid('cell_type ~ time_point') + labs(title="Counts comparison between technical replicates (E12-High Glucose)",
                                                                x="Replicate-1",y="Replicate-2",size="Gene",color="Gene") + theme_classic(base_family = "Helvetica")+geom_point(color='darkgreen')


save(filename = 'e_12_high_glucose.png', height=5, width=5, units = 'in', dpi=1000)

/Users/krilowcn/anaconda3/envs/BINF/lib/python3.8/site-packages/plotnine/ggplot.py:727: PlotnineWarning: Saving 5 x 5 in image.
/Users/krilowcn/anaconda3/envs/BINF/lib/python3.8/site-packages/plotnine/ggplot.py:730: PlotnineWarning: Filename: e_12_high_glucose.png
/Users/krilowcn/anaconda3/envs/BINF/lib/python3.8/site-packages/plotnine/layer.py:467: PlotnineWarning: geom_point : Removed 32443 rows containing missing values.
/Users/krilowcn/anaconda3/envs/BINF/lib/python3.8/site-packages/plotnine/layer.py:467: PlotnineWarning: geom_point : Removed 32443 rows containing missing values.