In [95]:
import numpy as np
import pandas as pd

df = pd.read_csv('ABCC8_SNP_allele_calls.txt', delimiter = "\t", index_col=False)
df2 = df.assign(alt_allele = "") #create new dataframe for parsing


chrom_positions = df.position.unique() #grab all unique chromosome positions from dataframe
df2.head(5)

,sample,chrom,position,ref_allele,total_cov,count_A,count_C,count_G,count_T,count_ref,percent_ref,count_alt,percent_alt,alt_allele
0,s10_S10_L001,chr11,17415756,A,1,1,0,0,0,1,100.0,0,0.0,
1,s1_S1_L001,chr11,17415756,A,1,1,0,0,0,1,100.0,0,0.0,
2,s2_S2_L001,chr11,17415756,A,1,1,0,0,0,1,100.0,0,0.0,
3,s3_S3_L001,chr11,17415756,A,1,1,0,0,0,1,100.0,0,0.0,
4,s5_S5_L001,chr11,17415756,A,2,2,0,0,0,2,100.0,0,0.0,

In [106]:
    
for idx, row in df2.iterrows():  #loop through the dataframe and perform the operations if the chromosome position, 'i'
    alt_allele_a = alt_allele_c = alt_allele_t = alt_allele_g = 0  #values of potential alt alleles to count/sum
    
    
    
    for pos in chrom_positions:
        max_value = 0
        if row['position'] == 17415771:
            alt_allele_a = row['count_A'] + alt_allele_a
            alt_allele_c = row['count_C'] + alt_allele_c
            alt_allele_g = row['count_G'] + alt_allele_g
            alt_allele_t = row['count_T'] + alt_allele_t
            allele_list = [alt_allele_a ,alt_allele_c, alt_allele_t, alt_allele_g]
     
            
            print(allele_list)
            
#             if row['percent_ref'] == 100:
#                 df2.at[idx , 'alt_allele'] = 0
    #        print(row[3:6])
        break
#     if row['count_A'] > max_value & row['count_A'] < 1000:
#         allele="A"
#         df2.at[idx , 'alt_allele'] = allele
#     if row['count_C'] > max_value & row['count_C'] < 1000 :
#         allele="C"
#         df2.at[idx , 'alt_allele'] = allele
#     elif row['count_T'] > max_value & row['count_T'] < 1000:
#         allele="T"
#         df2.at[idx , 'alt_allele'] = allele
#     elif row['count_G'] > max_value & row['count_G'] < 1000:
#         allele="G"
#         df2.at[idx , 'alt_allele'] = allele
#     else:
#         allele="N/A"
#         df2.at[idx , 'alt_allele'] = allele

    #df2.at[idx , 'alt_allele'] = allele

[0, 8011, 3, 0]
[0, 8010, 4, 0]
[0, 8011, 2, 0]
[0, 8006, 8, 0]
[1, 8012, 0, 0]
[0, 8012, 1, 0]
[0, 8010, 3, 0]
[0, 8011, 1, 0]
[0, 8013, 0, 0]
[0, 8008, 5, 0]
[1, 8010, 2, 0]

In [32]:
df_chrom_post = dict()
for k, v in df2.groupby('position'):
    df_chrom_post[k] = v

In [ ]:
for idx, row in df2.items():
    for i in chrom_positions:
        print(df_chrom_post[i])